### ISSUE TITLE
[Feature request] Modal video and video library window

### ISSUE THREAD

**Issue by timdonovanuk** [twrecked/lovelace-hass-aarlo#54] opened 2020-12-29 13:26 UTC
I display my cameras in very small thumbnails because most of the time I'm not interested in them taking up realestate on my dashboard. However, this means when trying to view them, or the library, its crammed in to a very small square.

![image](https://user-images.githubusercontent.com/8156439/103287020-5ce25600-49d9-11eb-8cf2-a84c83aa7e99.png)

The default HA picture-glance lovelace card opens a modal window when you click on a camera feed - could this do something similar?

I was thinking this would be a good use of the image_click attribute. Options like `image_click: modal-play_last, modal-play_live and modal-library` would be neat!

**Comment by twrecked** [comment] 2021-01-24 22:46
I'll take a look. I'm not a javascript programmer but I'll see what I can do!

**Comment by twrecked** [comment] 2021-01-26 05:07
I kind of have it working. I'm thinking the final options will be something like:

`image_click:`
  - `play`; live stream,
  - `modal-play`; live stream in modal window
  - `modal-last`; play last recording in modal window
  anything else is last as now

`library_click:`
  - `modal`; play recording in modal window
  anything else plays as now

**Comment by twrecked** [comment] 2021-01-26 18:59
#55 contains experimental support; let me know how it loops

**Comment by krelltunez** [comment] 2021-01-27 18:05
I added "modal-last" to the image_click option and "modal" to the library_click option, but I can't tell if it's acting any differently - other than that instead of showing the live image, it shows the last recorded one (which I can confirm).

What should the "modal" window look like?

**Comment by twrecked** [comment] 2021-01-27 18:15
It should be pretty obvious, it will open up a big window to show the video instead of showing it in the card.

**Comment by krelltunez** [comment] 2021-01-27 19:57
> It should be pretty obvious, it will open up a big window to show the video instead of showing it in the card.
> 
> Did you refresh? It may still be using the old card.

That's how I thought it would work.

I had tried refreshing and even cleared my browser cache and it was still showing up within the card.  Did a reboot and it's now working as expected.  I didn't think a reboot would be required but it was (at least for me).

So far it works as expected and is a great enhancement.  I'll keep testing and report back any unexpected behavior.

**Comment by twrecked** [comment] 2021-01-27 20:06
Glad it's working. You shouldn't need a reboot - at least I didn't when testing here - but sometimes home assistant can be funny about these things. One question, what OS and browser? I have a limited set of things I can try it on so it'd be good to know what it works on.

Also, I forgot one piece in the documentation; you can add `modal_multiplier` to change the window size. The default is 0.7 and it can be different for each card.

```yaml
image_click: modal-play
library_click: modal
modal_multiplier: 0.5
```

**Comment by krelltunez** [comment] 2021-01-27 20:09
Tried using Windows 10 and Chrome (v88.0.4324.104).  The default size looks good to me but will keep that in mind.

**Comment by krelltunez** [comment] 2021-01-28 01:12
Noticing the behavior of this on my android phone is wonky. When I tap on the camera image, the card goes gray and after a bit the modal window with the video shows up in the top left (like off the area of the screen). Scrolling up I can see the video but it's tiny (i.e., smaller than the card).

**Comment by twrecked** [comment] 2021-01-28 01:37
Same here. I've got to figure out how to get that going.

**Comment by krelltunez** [comment] 2021-02-07 13:57
I've been testing the alpha release and it's working well. I especially like being able to change the number of thumbnails in the library grid, not to mention the highlighting of the thing that set off the recording (vehicle, animal, person). Much easier to see details in the 2x2.

I'm posting here because while the modal window support works great on my computer, it's not functioning on my phone. The modal window opens but all I see is the same image from the thumbnail (in other words the video doesn't play). Also, because I can't trigger it to show the playback controls, I have to guess where the stop button is (bottom left) to close it.

So, I'm excited to see that you're planning to have an option to turn this off on phones. Alternatively, if you could force it to landscape view this might be pretty cool.

I'll keep updating and re-testing.

Thanks!!

**Comment by twrecked** [comment] 2021-02-07 14:18
The modal window on the phone is... erm... turning out to be interesting. I will definitely give the option to turn it off for mobile devices, I'll also try and find a better modal library and see if that helps.

Maybe get it go straight to fullscreen on mobile would be better.

**Comment by twrecked** [comment] 2021-02-12 14:27
I updated to add different modal options. There is now a "smart" option that will do modal on desktop, non-modal on mobile devices.

And going straight to full screen is not an option, browsers - for good reasons - don't allow that to happen.

**Comment by krelltunez** [comment] 2021-02-12 15:13
That works great!  Works as expected.  Quick question, though - per the docs, the options supported are ['modal','smart','stream','recording'].  I switched to 'smart' which plays the last recorded video.  Is there a way to have it still be 'smart' but instead stream?  Previously, I used 'modal-play'.

**Comment by twrecked** [comment] 2021-02-12 15:20
You can combine them.

```
"smart,stream"
```

**Comment by krelltunez** [comment] 2021-02-12 15:23
Hmm, I did that and now get a gray screen when I click the image.

**Comment by twrecked** [comment] 2021-02-12 15:26
Ah. Bug then. I'll fix it. You will be able to do it.

**Comment by krelltunez** [comment] 2021-02-12 17:54
No... stays gray.

**Comment by twrecked** [comment] 2021-02-15 23:33
Sorry, I got sidetracked. What version of `aarlo` and `lovelace-aarlo` are you on?

Do you have `direct` play set?

I made some changes to the user agent which might have broken things.

**Comment by krelltunez** [comment] 2021-02-18 23:42
Sorry I missed your reply.  Good news/bad news.  Running alpha 15 of `lovelace-aarlo` and 0.7.1.beta.2 of `aarlo`.

Square aspect ratio for my doorbell is GONE.  Shows up in Lovelace as wide, like other cameras.  Checked and the config still says "square".

That said, the modal stream now works!  There's a slight delay but that's to be expected.  Regarding your question about `direct` play, I'm a little lost.  Here's my doorbell card:

door: binary_sensor.front_door_ias_zone
door_bell: binary_sensor.aarlo_ding_front_door
entity: camera.aarlo_front_door
aspect_ratio: square
image_click: 'smart,stream'
library_click: smart
library_sizes:
  - 2
name: Front Door
show:
  - motion
  - sound
  - snapshot
  - signal_strength
  - battery_level
  - captured_today
top_date: false
top_status: false
top_title: true
type: 'custom:aarlo-glance'

**Comment by krelltunez** [comment] 2021-02-19 02:01
Never mind, got the square back after reading the docs.  I realized `square` now goes under `image_view`.

**Comment by krelltunez** [comment] 2021-02-19 02:03
Hmmm, I added `direct` and now the modal windows are back to gray.

Need to take a break and spend some family time - back to this later!

**Comment by twrecked** [comment] 2021-02-19 03:07
I broke this. I updated the default user agent not realizing I would break some existing installs so I reverted the change. To get direct streaming to work you need 2 pieces:

In you `aarlo` section of `configuration.yaml` make sure to set the user agent:. This controls the type of stream we get from Arlo.

```yaml
  user_agent: linux
````

And, as you worked out, add `direct` onto your Lovelace card configuration.

**Comment by krelltunez** [comment] 2021-02-19 03:10
Thanks!!!  I edited/condensed my earlier posts.  No wonder `direct` streaming did not work!  I'll try this later when I can reboot after modifying my config yaml file.

**Comment by twrecked** [comment] 2021-02-19 04:52
Excellent. I'm going to improve the README files for this and `hass-aarlo` when I've finished all this coding.

Be sure to copy your old config before using this one; as an example, this is your doorbell card using the new config:

```yaml
entity: camera.aarlo_front_door
name: Front Door
door: binary_sensor.front_door_ias_zone
door_bell: binary_sensor.aarlo_ding_front_door
image_view: 'square,direct'
image_click: 'smart,stream'
image_top: 'name'
image_bottom: 'status,motion,sound,snapshot,signal,battery,library'
library_click: smart
library_sizes:
  - 2
type: 'custom:aarlo-glance'
```

**Comment by krelltunez** [comment] 2021-02-19 05:06
Everything is working great!  The only thing I've noticed is that my cameras switch to "Recently Active" when I'm done streaming.  My doorbell, on the other hand, still says "Streaming" long after I stopped streaming.  I also put `stream` in `image_bottom` and noticed a square "stop" button appears, instead of going back to the "play" button.  This also stops me from being able to stream the doorbell again.

**Comment by twrecked** [comment] 2021-02-19 05:18
Noted. I'll take a look. I might have missed a "stream has stopped" notification.

**Comment by krelltunez** [comment] 2021-02-19 05:23
Also just switched to my mobile device for bedtime and...

![Screenshot_20210218-232104_Home Assistant](https://user-images.githubusercontent.com/8503323/108461383-3f46a580-7240-11eb-9092-525d46104438.jpg)

**Comment by twrecked** [comment] 2021-02-19 05:27
Crap. The mobile script caching is really, really annoying, it will still be using an old version of the card. 

I would flip your config back for now. Or try reloading a few times.

**Comment by krelltunez** [comment] 2021-02-19 05:47
Came back after a bit. Working now in the mobile app.

**Comment by krelltunez** [comment] 2021-02-19 16:03
Everything seems to be working well this morning except for the doorbell still saying it's streaming.  I noticed that when it does this, it stops registering/recording new motion/activity.  I'll reboot to reset it and will only try streaming from that device again if you push a fix.  Unfortunately, it's one of the ones I check most often.

My only other feedback/question is whether there's any way to order the icons on the image_bottom.  I have some OCD issues and would like to be able to put them in the order I want.

I absolutely LOVE the ability to place toggles on the card for chimes, lights and locks, as well as being able to show if a door is open.  Fantastic work!

Can I push a donation your way?  I feel like you've been doing a lot of work on this lately and would like to buy you a coffee/tea/beer/wine as a token of my appreciation.

**Comment by twrecked** [comment] 2021-02-20 19:21
When the doorbell says it's streaming, what is it showing in the Arlo app? 

It might help to get some debug from the backend.

As for ordering, I've been thinking about that, and I don't think it's a huge change. If I did it I would just honor the order given in the image_bottom list, as much as I can.

**Comment by krelltunez** [comment] 2021-02-21 17:06
So here's what I see when this happens.  Modal window opens, current video streams.  Stopping the stream returns me to the main HA window, and the snapshot updates (same as with other cameras), BUT it still says streaming in the top right and has the STOP square button on the bottom.  The Arlo app also has the snapshot updated, and says "3m ago" in the top left (which is when I stopped the stream).  Everything else _appears_ normal in the Arlo app, but as stated before, no recordings happen - it's as if the camera becomes unresponsive.

BTW, the turn on/off switch isn't working for the doorbell either.  Clicking it turns it off (though no change is shown in HA like other cameras).  Arlo app reports camera is off.  Clicking the switch again (which of course is still the "off" button) in HA does NOT turn it back on, I have to go into the Arlo app to do that.

If you want to debug, I can turn that stuff back on and work through this tomorrow.  Too much family stuff going on to spend time on this today!  Thanks again for all your help working through my doorbell issues!

**Comment by twrecked** [comment] 2021-02-23 03:58
@krelltunez  I just put ordering into the latest release, let me know if it works.

As for the other pieces; I'm guessing it must be something unique to the Video Doorbells. The best debug we can get will be from Chrome's developer tools. We need to log into the my.arlo.com website and turn the camera off and on and start and stop the stream on there. We'll be able to see what packets Arlo sends out. It's gotten late here, I'll dig some instructions out later.

**Comment by krelltunez** [comment] 2021-02-23 16:16
Cool!  Took some finagling to get this to work (relating to Chrome cache issues), finally got it going.  Works well BUT it wipes out the other icons I had configured for doors, lights, locks and chimes.  Do I need to do something differently to retain those?

As for the video doorbell weirdness, I would be happy to provide video doorbell debugging info from my.arlo.com whenever you have time.  I will definitely need instructions, but I'm happy to give it a shot!

**Comment by twrecked** [comment] 2021-02-23 16:32
The new configuration doesn't automatically put the other icons on the display. You need to explicitly add them as part of the configuration. And they can be placed anywhere.

This will look like the old config:

```yaml
image_bottom:
  - 'previous,sound,motion,battery,library,stream,snapshot'
  - 'door,lock,bell,light,next'
 ```

Or for something completely different:
```yaml
image_top:
  - 'door,lock,bell,light,next'
  - 'previous,sound,motion,battery,library,stream,snapshot'
 ```

And you can edit the configuration without worrying about the caching!

**Comment by krelltunez** [comment] 2021-02-23 17:09
Ahhh!  LOL, I totally missed that.  I wish I could see track changes of the docs when changes are made!  

This is absolutely awesome!!!

**Comment by twrecked** [comment] 2021-02-23 17:38
My phone and tablets are a pain too. I end up enabling USB debugging on my phone and reloading that way.

**Comment by twrecked** [comment] 2021-02-24 01:39
I think for the doorbell we should start with the Home Assistant debug. You'll need to restart Home Assistant with `aarlo` debugging enabled. Set up the logger like this:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
And add extra options to your `aarlo` config:

```yaml
aarlo:
  verbose_debug: True
```

With that debug enabled start the stream and attempt to stop it. The debug is at `/config/homeassistant.log` and there are timestamps in the debug which should help you locate the bits we are interested in, you are looking for:

-  `'activityState': 'userStreamActive'`; this will happen when the stream starts, there will be a `url=rtsps` or `url=https` a few lines above
-  `stop_activity`; this happens when we request the stream stop
-  `'activityState': 'idle'`; this happens when the stream actually stops

If you can copy the lines around all this and attach them here that would be great. You can use [this website](https://pyaarlo-tfa.appspot.com/) to encrypt them so only I can read them.

**Comment by krelltunez** [comment] 2021-02-26 21:00
Weird - I don't get notifications of your new replies anymore.  I didn't know you were ready to kick off debugging on the doorbell streaming.  I'll get that going tonight/this weekend.

That said, I've got the latest of both the Lovelace card and Add-On installed and I'm having some issues with my setup.  

1. Modal or smart playback seems super glitchy.  Sometimes it opens a modal window, sometimes it doesn't.  Something I just did seems to have gotten it to work.  Weirdly, this seems to tie to 4 below, because it was only acting up at the same time I saw the numerical library icons.

2. Am I right that `library_click` went away?  Now, if I click a thumbnail in my recording library, it only opens in the card.

3. Streaming does NOT work.  It shows the last snapshot and never does anything.  This is on regular cameras, not even my doorbell.  And I've waited a LONG time to see if it will start - it doesn't.

4. I can't get the numerical icons to stay.  I've tried clearing browser cache, closing/reopening, different browsers, etc.  I've only gotten it to show once (switched computers) and then issue 1 happened, but now it's gone again.

Here's how I have one of my cards configured (they're all about the same) - is something here wrong?

`entity: camera.aarlo_backyard_pro_2
name: Backyard
door: binary_sensor.back_door_ias_zone
light: switch.back_yard_house_lights
global: 'muted,numerical'
image_view: 'diect,smart'
image_top: 'name,,,library,stream|status'
image_bottom: 'onoff,motion,sound,signal,battery|door,light'
image_click: recording
library_view: download
library_sizes: '2,3,4'
type: 'custom:aarlo-glance'`

**Comment by twrecked** [comment] 2021-02-26 21:25
If you copy/pasted that then it should be `direct` not `diect`. That could explain the streaming.

As for the others, what browser/os is this on?

**Comment by twrecked** [comment] 2021-02-26 21:42
Sorry; the new config is in a state of flux as I'm trying to put pieces into their place in the view hierarchy and I missed some stuff out of the README. I'll update that stuff later.

This card should work better:

```yaml
entity: camera.aarlo_backyard_pro_2
name: Backyard
door: binary_sensor.back_door_ias_zone
light: switch.back_yard_house_lights
global: muted
image_view: 'direct,smart,numeric'
image_top: 'name,,,library,stream|status'
image_bottom: 'onoff,motion,sound,signal,battery|door,light'
image_click: recording
library_view: download
library_sizes: '2,3,4'
type: 'custom:aarlo-glance'
```

**Comment by krelltunez** [comment] 2021-02-26 23:45
No sweat!  The numeric works now.  Streaming as well (thanks for noticing my stupid typo).  I'll play around with it some more.

Will also turn the debugging on soon.  Thanks!!

**Comment by twrecked** [comment] 2021-02-28 04:12
I always forget to ask, but what version of Home Assistant are you on?

**Comment by krelltunez** [comment] 2021-02-28 13:16
Always the latest... Right now I'm on 2021.2.3.

**Comment by krelltunez** [comment] 2021-02-28 20:36
OK, posting my results!  I pressed stream at 14:24:24.  Let it run for a bit and pressed stop at 14:25:00.

Interestingly, at the start of the stream I see the following (which differs from what you said above):  'activityState': 'startUserStream'

I won't try to interpret anything though!  I hope this helps!!

[HA Log Encrypt.txt](https://github.com/twrecked/lovelace-hass-aarlo/files/6057907/HA.Log.Encrypt.txt)

**Comment by twrecked** [comment] 2021-03-02 13:23
Yes. You're not getting the `userStreamActive` at all. Interesting. I'll look at that:

Just to clarify, is this on a desktop machine? If so, what type?

Can you try non-direct streaming. If you have the latest `hass-aarlo` installed (beta.4)  you can just remove `direct` from the `image_view` options.

**Comment by krelltunez** [comment] 2021-03-02 16:54
My HA is the OS (supervised) version installed on a RPi 4.

The machine I use mostly to access it is a Windows 10 machine, or my Android tablet or phone (both Samsung using the companion app).

Having turned off `direct` under `image_view`, the steam doesn't even start - instead I just see the last snapshot in the modal window.  With `direct` turned on, I see that initially, but the stream will start after a short delay while the camera connects, starts streaming, etc.

**Comment by twrecked** [comment] 2021-03-02 17:38
Which browser on Windows 10? I'll boot into Windows 10 and try tonight.

**Comment by krelltunez** [comment] 2021-03-02 22:59
OK, after update to beta 4 and alpha 18... and removing `direct` from `image_view`, I'm seeing the same behavior.

My Windows 10 browser is Chrome.  Happy to try other ones if you want.

**Comment by twrecked** [comment] 2021-03-04 03:57
I tried Chrome on Windows 10 and it worked (these things always do...)

I think the issue is the browser is never connecting to the stream. Can you check the console on the browser and see if it's giving us any errors:

- Open Home Assistant in your browser
- CTRL+SHIFT+I then open the console on the tools (click the red cross and yellow triangle on the top right)
- Open a tab with a camera on it.
- CTRL+SHIFT+R
- Start a stream
- Look at the console, any strange errors coming out?

**Comment by krelltunez** [comment] 2021-03-04 15:20
I'll check this later today.  Right now, I'm dealing with my MQTT broker going down and causing other stuff in HA to stop working...

FYI, the stream starts and I can watch it so I'm not sure I understand, but I'll still follow the steps you mentioned (because I really don't understand any of this!).

Thanks.

**Comment by twrecked** [comment] 2021-03-04 18:09
:) I think I've lost track of what's actually broken. I've been trying to do too many things at once.

I thought the stream wasn't playing?

**Comment by krelltunez** [comment] 2021-03-04 19:26
No worries at all; no, that's not what's happening - so I'm glad I clarified.  Here's what's going on:

When I click stream on the video doorbell, all seems normal.  The stream starts playing as expected.  When I stop it, the window closes and the snapshot updates (like with other cameras) but it still says "Streaming" at the top and the triangular "play" button remains a square "stop" button.  On other cameras, when the stream is stopped it updates the snapshot, but indicates that it was "Recently Active" and the triangular "play" button returns.

It's as if the HA card isn't told that the steam stopped.  In the debugging we did, I was wondering if this has to do with the system receiving `startUserStream` instead of `userStreamActive`.  I thought I did see it coming back with `stop_activity` when I ended the stream and `idle` when it stopped, but maybe because this didn't tie back to the expected `userStreamActive` it wasn't closing the loop?  Just guessing; as I've said before this is all Greek to me.

![image](https://user-images.githubusercontent.com/8503323/110018710-326c8c00-7ced-11eb-846a-68eb6f946ba8.png)

**Comment by twrecked** [comment] 2021-03-04 20:43
I remember now. I'll revisit the debug!

I'll double check the `muted` code.

**Comment by twrecked** [comment] 2021-03-04 21:28
I think the problem was at the stop. Normally when we send an idle request to a camera we got an response saying the camera has moved to idle. The doorbell isn't sending that. The latest hass-aarlo beta `beta.5` might fix it.

**Comment by krelltunez** [comment] 2021-03-04 23:25
OK, I'll give it a try.  Right now, I'm experiencing issues on other parts of HA, so I'll return to this when I am able to iron those out.

**Comment by krelltunez** [comment] 2021-03-05 15:19
IT WORKS!  Not as instantaneously as other cameras (which switch to "Recently Active" right away).  At first I thought it was still acting weird, but when I looked back at the screen it had switched from "Streaming" to "Recently Active."  FYI, the video also played muted, so that's good.

HOORAY!  Thanks for all your help working through this!

**Comment by borski** [comment] 2021-03-15 02:47
Is there any way to get a way to close the modal? Right now it plays until it ends, so if you chose the wrong one, it can get very annoying :)

**Comment by krelltunez** [comment] 2021-03-15 03:38
If you hover over the modal window, you should have control buttons appear in the bottom left.  Sometimes you have to take the cursor outside the window and bring it back again to make it appear.

**Comment by twrecked** [comment] 2021-03-15 12:01
I just realized it's missing a "mousemove" event, I'll add that to make so just moving around on the video will make the controls appear.

**Comment by twrecked** [comment] 2021-03-15 13:15
In the latest release the controls should appear when you move the mouse on the video.

**Comment by krelltunez** [comment] 2021-03-15 15:59
Confirmed - working for me!

**Comment by twrecked** [comment] 2021-04-19 12:53
Modal support is working, closing. Any new bugs please open a new issue.

**Closed by twrecked** 2021-04-19 12:53 UTC
Labels: enhancement
