### ISSUE TITLE
Issue on Iphone?

### ISSUE THREAD

**Issue by BobRathke** [twrecked/lovelace-hass-aarlo#79] opened 2021-02-17 13:54 UTC
Hi Steve! Love your work! thank you!

I just installed AARLO and the associated custom lovelace card. Everything is working great with one exception. When I attempt to live stream the camera on my Iphone 10 all I get is a blank box. Any ideas?

**Comment by twrecked** [comment] 2021-02-17 14:34
Do you have direct streaming enabled?

And I just realized I do have some iPads lying around here - I'll see if they work for me here.

**Comment by BobRathke** [comment] 2021-02-17 14:46
I will confirm Direct streaming is enabled. It works fine on my PC with Firefox (with a few seconds of delay before the stream starts), just he Iphone has the issue.

**Comment by twrecked** [comment] 2021-02-17 17:20
Is it related to [this](https://github.com/twrecked/lovelace-hass-aarlo/issues/48).

**Comment by BobRathke** [comment] 2021-02-17 17:26
OK, thanks for the info. I did confirm I have direct streaming enabled & lovelace flag set. FYI - I am sseing this in the IOS HA client, not Safari (directly). I assume the IOS HA uses Safari?

Did I miss a recommendation to fix this in the thread you referenced?

**Comment by twrecked** [comment] 2021-02-17 17:36
No, there is recommendation yet. I honestly think the issue is at the Arlo end. Even if I set the `user_agent` to `apple` Arlo is sending me back an mpeg-dash stream which iPhones can't handle.

I will do some more digging.

**Comment by TheDK** [comment] 2021-02-19 09:37
@twrecked Do you have an iOS device for testing?

I just installed the most recent versions on my Dev VM, set `user_agent: linux` and `image_view: direct` in the card, on iPhone library videos won't start playing, live stream shows white window.

**Comment by twrecked** [comment] 2021-02-19 13:59
Not really. I have my daughter's iPhone but she's always out and about.

If you can do some testing that would be fantastic. These are a couple of things I think need to be tested:

- live stream my.arlo.com using an iPad
- live stream on my.arlo.com using a Mac

If/when they work we need the user agent and the protocol being used for the streaming.

**Comment by TheDK** [comment] 2021-02-19 15:48
Live Stream on iPhone does not work - there is no interface at all, Arlo directly throws me to the app. On iPad I get the same interface as on the PC, streaming and library views work. 

I have not found a way to view the user agent on mobile safari. I do not have a Mac, so no game here.

As it is working fine with the old card - which user agent is being used here?

**Comment by twrecked** [comment] 2021-02-19 15:56
A customized one. This seems to be very specific to an old Arlo device.

```python
                "Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) "
                "AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 "
                "(iOS Vuezone)"
```

You should be able to get the card working on iPhone again by removing `direct` from the Lovelace card and `user_agent` from the Arlo configuration, that way HA will convert it into a HLS stream.

**Comment by BobRathke** [comment] 2021-02-19 16:11
Hi Steve! I changed back to the HLS stream & it is now working on my Iphone 10X. I did still get this error, but it adventually started streaming on the Iphone..

Login attempt or request with invalid authentication from localhost (127.0.0.1). (Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2021.3 (io.robbie.HomeAssistant; build:2021.65; iOS 14.4.0) Mobile/HomeAssistant, like Safari)

Please let me know if there is something I can do to assist any farther!

Thanks again fo the quick update & your on going efforts are appreciated.
________________________________

**Comment by TheDK** [comment] 2021-02-19 16:36
I have removed direct and user_agent but can't get it to work in Mobile Safari - does HLS stream only work in the HA iOS companion app?

**Comment by twrecked** [comment] 2021-02-19 16:54
That's a good question. HLS is Apple's HTTP streaming protocol so I thought it would work on Safari.

I just checked my son's iPad and HLS streaming is working in Home Assistant inside Safari.

**Comment by TheDK** [comment] 2021-02-19 17:04
I played around a bit:
For videos in library when I click one it doesn‘t start. If I then click pause and play again it does start and work fine. Works on iPhone and iPad.

For live stream if I click on the image it shows a white screen. If I the select full screen I get the iPad video controls including pause. If I then click pause and play streaming works. Only works on iPad, on iPhone the Full screen control doesn’t work, so no play / pause button and no game.


Seems to me the stream does not trigger to start...

**Comment by twrecked** [comment] 2021-02-19 19:00
I think I know what's going on here. I can reproduce the not starting issue on my iPad here and I think it's because Safari won't allow videos with audio to autostart. I'll do some work on all this stuff and push a possible fix later on.

**Comment by TheDK** [comment] 2021-02-20 15:21
Tests showing promising results! Will migrate to prod environment over the weekend...

**Comment by twrecked** [comment] 2021-02-20 15:45
Excellent. Glad to hear it. I've got some tidy up to do but I wanted to get the code out and tested.

**Comment by TheDK** [comment] 2021-02-21 14:55
Now moved first card of prod to new release, works fine on iPhone, iPad (companion app) and browser (Firefox for me...) working fine. Also have to say documentation has improved greatly.

One question: The state of the cam in the standard top right of the window remains english. Would you like to include that into the language file?

**Comment by twrecked** [comment] 2021-02-21 15:22
Thanks for noticing the docs. This side of the project hadn't received much love in a long time so i figured it was due an update.

I think having the states in the language file is a good idea. I'll put it on the todo list.

**Comment by twrecked** [comment] 2021-02-23 04:00
@TheDK I just checked in the camera state language change to the master branch. If you look at `de.js` you'll see the entries in a new `state` section. There is also a new one at the `image` level.

**Comment by TheDK** [comment] 2021-02-23 13:30
Thanks, PR for German translation created...

**Comment by twrecked** [comment] 2021-03-04 03:53
I'm going to close this, iPhone working well for me.

**Closed by twrecked** 2021-03-04 03:53 UTC
